#
# Bambu Chamber Heater Modbus Controller for Sinilink XY-SA/ST series temperature controllers using the
# ESP8285 (XY-WFPOW) microcontroller. Designed to work with Bambu 3D Printers as a chamber heater controller.
# Copyright (C) 2026    Katherine Dubé
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# ========================================
# FAHRENHEIT CONFIGURATION
# ========================================
# This file defines temperature unit settings and number entities for Fahrenheit operation.
# To use Celsius instead, modify the include in temperature_controller.yaml to use celsius.yaml
#
# Temperature ranges are set to match the physical controller's capabilities:
#   - Operating thresholds: 32-185°F (0-85°C)
#   - Alarm limits: -40-230°F (-40-110°C)
#   - Calibration offset: ±18°F (±10°C)

substitutions:
  temp_unit: "Fahrenheit"
  temp_unit_label: "°F"

globals:
  # Filament-specific temperature presets with ±1°F hysteresis
  # Hysteresis prevents rapid relay cycling (chatter) by creating a 2°F operating band
  # Format: {start_temp, stop_temp} where start < stop for heating mode
  # Preset temps are defined in Celsius in main config, then converted here
  # Example: PLA at 22°C (71.6°F) becomes 70.6-72.6°F range
  # Note: For cooling mode, you would configure these with start > stop
  - id: filament_presets
    type: std::map<std::string, std::pair<float, float>>
    initial_value: |-
      []() {
        auto c_to_f = [](float c) { return c * 9.0f / 5.0f + 32.0f; };
        std::map<std::string, std::pair<float, float>> presets;
        presets[std::string("PLA")] = {c_to_f(${pla_temp}) - 1, c_to_f(${pla_temp}) + 1};
        presets[std::string("PETG")] = {c_to_f(${petg_temp}) - 1, c_to_f(${petg_temp}) + 1};
        presets[std::string("ABS")] = {c_to_f(${abs_temp}) - 1, c_to_f(${abs_temp}) + 1};
        presets[std::string("ASA")] = {c_to_f(${asa_temp}) - 1, c_to_f(${asa_temp}) + 1};
        presets[std::string("Nylon")] = {c_to_f(${nylon_temp}) - 1, c_to_f(${nylon_temp}) + 1};
        return presets;
      }()

number:
  # ========================================
  # TEMPERATURE THRESHOLDS (Operating Range)
  # ========================================
  # These define when the relay turns on/off during normal operation
  # Heating mode: low < high (e.g., start at 70°F, stop at 73°F)
  # Cooling mode: low > high (e.g., start at 73°F, stop at 70°F)
  # Range limited to safe operating range: 32-185°F
  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Low Temp Threshold"
    address: 0x0006
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "${temp_unit_label}"
    min_value: 32
    max_value: 185
    step: 0.1
    mode: box
    entity_category: config
    lambda: "${temp_read_lambda}"
    write_lambda: "${temp_write_lambda}"
    id: temp_threshold_start
    icon: "mdi:temperature-low"
    web_server:
      sorting_group_id: sorting_group_settings

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "High Temp Threshold"
    address: 0x0007
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "${temp_unit_label}"
    min_value: 32
    max_value: 185
    step: 0.1
    mode: box
    entity_category: config
    lambda: "${temp_read_lambda}"
    write_lambda: "${temp_write_lambda}"
    id: temp_threshold_stop
    icon: "mdi:temperature-high"
    web_server:
      sorting_group_id: sorting_group_settings

  # ========================================
  # TEMPERATURE ALARMS (Safety Limits)
  # ========================================
  # These trigger emergency stops when exceeded (if over_temp_shutoff enabled)
  # Set beyond normal operating range to catch dangerous conditions
  # Example: If operating at 140°F, set high alarm to 158°F, low alarm to 41°F
  # Both heating and cooling modes can use these alarms for safety
  # Range: -40-230°F (controller's full measurement range)
  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "High Temp Alarm"
    address: 0x0008
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "${temp_unit_label}"
    min_value: -40
    max_value: 230
    step: 0.1
    mode: box
    entity_category: config
    lambda: "${temp_read_lambda}"
    write_lambda: "${temp_write_lambda}"
    id: high_temp_alarm
    icon: "mdi:temperature-chevron-up"
    web_server:
      sorting_group_id: sorting_group_settings

  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Low Temp Alarm"
    address: 0x0009
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "${temp_unit_label}"
    min_value: -40
    max_value: 230
    step: 0.1
    mode: box
    entity_category: config
    lambda: "${temp_read_lambda}"
    write_lambda: "${temp_write_lambda}"
    id: low_temp_alarm
    icon: "mdi:temperature-chevron-down"
    web_server:
      sorting_group_id: sorting_group_settings

  # ========================================
  # TEMPERATURE CALIBRATION
  # ========================================
  # Offset applied to temperature sensor reading for calibration
  # Positive values increase displayed temperature, negative values decrease
  # Example: If sensor reads 70°F but actual is 72°F, set offset to +2.0
  # Range: ±18°F (±10°C)
  - platform: modbus_controller
    modbus_controller_id: modbus_device
    name: "Temp Offset"
    address: 0x000B
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "${temp_unit_label}"
    min_value: -18 
    max_value: 18
    step: 0.1
    mode: box
    entity_category: config
    lambda: "${temp_read_lambda}"
    write_lambda: "${temp_write_lambda}"
    id: temp_offset
    icon: "mdi:temperature-plus"
    web_server:
      sorting_group_id: sorting_group_settings